services:
  db:
    image: postgres:13
    env_file:
      - ./env/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - webnet

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    env_file:
      - ./env/.env.backend
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - webnet
    expose:
      - "8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          cpus: '16'
          memory: 24g
    init: true

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - webnet
    volumes:
      - static_volume:/staticfiles

volumes:
  postgres_data:
  static_volume:

networks:
  webnet: