# Generated by Django 5.1.2 on 2024-10-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencegroup',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Штрихкод'),
        ),
    ]
