# Generated by Django 5.1.2 on 2024-11-22 15:51

from django.db import migrations


def initialize_evidence_group_count(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    EvidenceGroup = apps.get_model('core', 'EvidenceGroup')

    for department in Department.objects.all():
        count = EvidenceGroup.objects.filter(case__department=department).count()
        department.evidence_group_count = count
        department.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_department_evidence_group_count_and_more'),
    ]

    operations = [
        migrations.RunPython(initialize_evidence_group_count),
    ]
