# Generated by Django 5.1.3 on 2024-12-01 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_case_status_case_core_case_status_59308c_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='session',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='session',
            name='login',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Выход'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biometric_registered',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Биометрия зарегистрирована'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('AKMOLA', 'Акмолинская область'), ('AKTOBE', 'Актюбинская область'), ('ALMATY_REGION', 'Алматинская область'), ('ATYRAU', 'Атырауская область'), ('EAST_KAZAKHSTAN', 'Восточно-Казахстанская область'), ('ZHAMBYL', 'Жамбылская область'), ('WEST_KAZAKHSTAN', 'Западно-Казахстанская область'), ('KARAGANDA', 'Карагандинская область'), ('KOSTANAY', 'Костанайская область'), ('KYZYLORDA', 'Кызылординская область'), ('MANGYSTAU', 'Мангистауская область'), ('PAVLODAR', 'Павлодарская область'), ('NORTH_KAZAKHSTAN', 'Северо-Казахстанская область'), ('TURKESTAN', 'Туркестанская область'), ('ASTANA', 'город Астана'), ('ALMATY_CITY', 'город Алматы'), ('SHYMKENT', 'город Шымкент')], db_index=True, max_length=50, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REGION_HEAD', 'Главный пользователь региона'), ('DEPARTMENT_HEAD', 'Главный по отделению'), ('USER', 'Обычный пользователь')], db_index=True, default='USER', max_length=20, verbose_name='Роль'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['login'], name='core_sessio_login_09e692_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['logout'], name='core_sessio_logout_6e3684_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['active'], name='core_sessio_active_ad5f20_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='core_user_usernam_e8adca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='core_user_first_n_9988cb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='core_user_last_na_cc993d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='core_user_phone_n_59ea9a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['rank'], name='core_user_rank_0de3c3_idx'),
        ),
    ]
